name: 'javascript-action-tutorial'
description: 'Action for tutorial'
inputs:
  owner:
    description: 'The owner of the repository(user or org)'
    required: true
  repo:
    description: 'The repository name'
    required: true
  pr_number:
    description: 'The number of the PR'
    required: true
  token:
    description: 'The token to use to access the Github API'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
