name: "units-test"
on:
  pull_request_target:
    types: [opened, reopened,synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: effgenij/javascript-action-tutorial@main
      with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        pr_number: ${{ github.event.number }}
        token: ${{secrets.GITHUB_TOKEN}}
